# Generated by Django 4.2.9 on 2024-03-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Display', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
