services:

    web:
      build:
        context: ./Transcendence/
      command: gunicorn Transcendence.wsgi:application --bind 0.0.0.0:8000
      volumes:
        - ./Transcendence/:/usr/src/app/
        - static_files:/usr/src/app/staticfiles
      expose:
        - 8000
      env_file:
        - ./.env/dev.env

    nginx:
      build:
        context: ./nginx/
      ports:
        - 443:443
      volumes:
        - ./nginx/conf.d/:/etc/nginx/conf.d/
        - static_files:/home/app/staticfiles


volumes:
  static_files: