# Generated by Django 4.2.8 on 2023-12-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field1', models.CharField(max_length=100)),
                ('field2', models.TextField()),
                ('field3', models.IntegerField()),
                ('field4', models.BooleanField(default=False)),
                ('field5', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
