# Generated by Django 4.2.8 on 2023-12-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_A_P', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='field5',
            field=models.DateTimeField(),
        ),
    ]
