# Generated by Django 4.2.8 on 2023-12-22 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('S_A_P', '0003_remove_yourmodel_field5'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='field5',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
