# Generated by Django 4.2.8 on 2023-12-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_A_P', '0004_yourmodel_field5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='field5',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
