# Generated by Django 4.2.8 on 2023-12-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_A_P', '0006_remove_yourmodel_field5'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=0),
        ),
    ]
