# Generated by Django 4.2.8 on 2023-12-22 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('S_A_P', '0007_yourmodel_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='field6',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
