# Generated by Django 4.2.8 on 2023-12-22 16:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('S_A_P', '0008_yourmodel_field6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='field6',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
