# Generated by Django 4.2.8 on 2023-12-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('S_A_P', '0012_yourmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='field1',
            field=models.CharField(default='HELLO', max_length=100),
        ),
    ]
