# Generated by Django 5.0 on 2024-01-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
    ]
