# Generated by Django 5.0 on 2024-02-08 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_blockeduser_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='blockeds',
            field=models.ManyToManyField(blank=True, related_name='blockeds', to='chat.blockeduser'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
