# Generated by Django 5.0 on 2024-01-05 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
