# Generated by Django 5.0 on 2024-02-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_customuser_best_score_customuser_draw_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='score',
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_score',
            field=models.IntegerField(default=31),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='best_score',
            field=models.IntegerField(default=31),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='draw',
            field=models.IntegerField(default=31),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lose',
            field=models.IntegerField(default=31),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='win',
            field=models.IntegerField(default=31),
        ),
    ]
