# Generated by Django 5.0 on 2024-02-14 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_customuser_score_customuser_total_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='total_score',
            new_name='total_match',
        ),
    ]
