# Generated by Django 5.0 on 2024-01-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_myuser_friends'),
    ]

    operations = [
        migrations.DeleteModel(
            name='myUser',
        ),
    ]
