# Generated by Django 4.2.8 on 2024-02-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_total_score_customuser_total_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jwt_secret',
            field=models.CharField(default='', max_length=100),
        ),
    ]
