# Generated by Django 4.2.9 on 2024-03-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='best_score',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='draw',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_match',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='win',
            field=models.IntegerField(default=0),
        ),
    ]
