# Generated by Django 4.2.9 on 2024-03-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
