# Generated by Django 4.2.9 on 2024-02-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(default='profile_photo/default.jpg', upload_to='profile_photo/'),
        ),
    ]
