# Generated by Django 5.0.1 on 2024-02-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_customuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(blank=True, default='profile_photo/default.jpg', null=True, upload_to='profile_photo/'),
        ),
    ]
