# Generated by Django 4.2.9 on 2024-03-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_remove_customuser_best_score_remove_customuser_draw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('TR', 'Turkish'), ('FR', 'French'), ('EN', 'English')], default='EN', max_length=2),
        ),
    ]
