# Generated by Django 4.2.9 on 2024-03-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_customuser_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_42_student',
            field=models.BooleanField(default=False),
        ),
    ]
