# Generated by Django 4.2.9 on 2024-03-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0002_customuser_online_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.CharField(default='profile_photo/default.jpg', max_length=128),
        ),
    ]
