# Generated by Django 4.2.9 on 2024-03-03 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0003_customuser_is_42_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_42_student',
        ),
    ]
