# Generated by Django 5.0.1 on 2024-02-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
    ]
