# Generated by Django 4.2.9 on 2024-03-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0004_alter_customuser_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
    ]
