# Generated by Django 4.2.9 on 2024-03-09 19:04

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_remove_customuser_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='profile_photo/default.jpg', upload_to=Chat.models.CustomUser.where_to_upload),
        ),
    ]
