# Generated by Django 4.2.9 on 2024-03-19 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0006_alter_customuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('TR', 'Turkish')], default='EN', max_length=2),
        ),
    ]
