# Generated by Django 4.2.9 on 2024-03-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0008_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_42_student',
            field=models.BooleanField(default=False),
        ),
    ]
