# Generated by Django 4.2.9 on 2024-03-09 22:35

import Chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0010_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='default/default.jpg', upload_to=Chat.models.CustomUser.where_to_upload),
        ),
    ]
