# Generated by Django 4.2.9 on 2024-03-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Chat', '0010_alter_customuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('TR', 'Turkish'), ('EN', 'English'), ('FR', 'French')], default='EN', max_length=2),
        ),
    ]
