version: '3.3'

services:
  back:
    container_name: back
    image: back
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 6969:8000
    networks:
      - default
    restart: always

  db:
    container_name: db
    image: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    build:
      context: ./
      dockerfile: docker.dockerfile
    restart: always
    ports:
      - 5432:5432
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]

networks:
  default:
    driver: bridge