version: '3.3'

services:
  back:
    container_name: back
    image: back
    build:
      context: ./backdoor
      dockerfile: Dockerfile
    ports:
      - 6969:6969
    networks:
      - default
    restart: always
    volumes:
      - ./backdoor/data:/transcendence

networks:
  default:
    driver: bridge