# Generated by Django 4.2.9 on 2024-03-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PongInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_id', models.CharField(max_length=100)),
                ('invitee', models.CharField(max_length=100)),
                ('invited', models.CharField(max_length=100)),
                ('is_active', models.IntegerField(default=0)),
            ],
        ),
    ]
