# Generated by Django 4.2.9 on 2024-03-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_ponginvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponginvite',
            name='is_active',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
