# Generated by Django 4.2.9 on 2024-02-29 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ScoreOne', models.IntegerField(default=0)),
                ('ScoreTwo', models.IntegerField(default=0)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Loser', to=settings.AUTH_USER_MODEL)),
                ('Winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
