# Generated by Django 4.2.9 on 2024-03-07 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Api', '0002_ponginvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=False, serialize=False, verbose_name='ID')),
                ('ScoreOne', models.IntegerField(default=0)),
                ('ScoreTwo', models.IntegerField(default=0)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('UserOne', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='UserOne', to=settings.AUTH_USER_MODEL)),
                ('UserTwo', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='UserTwo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('UserOne',),
            },
        ),
    ]
