# Generated by Django 5.0 on 2024-02-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_match'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ('Winner',)},
        ),
    ]
