# Generated by Django 4.2.9 on 2024-03-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_ponginvite_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponginvite',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
